version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: mvc-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=12345678
        - MYSQL_DATABASE=mvc
        - MYSQL_USER=mvc
        - MYSQL_PASSWORD=12345678
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: mvc-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: mvc-php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

